Exercise11
Kelliep11/-DevOps-Course-Starter2 pull request #12
Opened 2022-12-08 14:30 UTC by Kelliep11

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps requested changes
Thank you for the submission. The implementation code looks good.

Unfortunately the website is currently down - you will need to fix it and make sure your documentation is up to date in case it requires some additional setup.

Expand also on your `README.md` a little bit, so that the steps for authentication setup and updating your app in App Service are clearer to the new user.

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps commented on README.md
>  Website address https://kp01012022.azurewebsites.net/
The website is currently not working. You will need to fix this before we can check the functionality is working as expected
![image](https://user-images.githubusercontent.com/92427951/207307940-491419f3-f939-4b99-aa1a-80b570da6830.png)

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps commented on README.md
> + Before merging, a new OAUTH app in github and set env variables in azure
Double check the wording here. It's not quite right

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps commented on README.md
> + Before merging, a new OAUTH app in github and set env variables in azure
It would be useful to have this expanded on, so that someone who is new to this project understands the steps involved

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps commented on todo_app/app.py
> +
There is a lot of these additional indentations. I think you may want to clean them up a bit so it's more consistent.

2022-12-13 11:44 UTC, CorndelWithSoftwireDevOps commented on README.md
>  Website address https://kp01012022.azurewebsites.net/
There is more info to confirm that the site is not working currently 
https://kp01012022.scm.azurewebsites.net/

![image](https://user-images.githubusercontent.com/92427951/207308765-4d2579df-2fc9-41b4-af0d-7d3748ef9760.png)

2023-01-13 11:46 UTC, merged

2023-01-13 11:57 UTC, JackMead commented
Thanks for fixing up your site, I was able to confirm that the website is now working and forced me through the authentication flow - nice!

As discussed on the call, it would be good to clarify the details in your Readme at a later point, but not critical here